version: "3"

services:
    poll:
      image: "poll"
      restart: always
      container_name: "poll"
      build: "./poll"
      ports:
        - "5000:80"
      depends_on:
        - "redis"
      networks:
        - "poll-tier"
      environment:
        - TESLA:"tesla"

    result:
      image: "result"
      restart: always
      container_name: "result"
      build: "./result"
      ports:
        - "5001:80"
      depends_on:
        - "db"
      networks:
        - "result-tier"
      environment:
        - TESLA:"tesla"

    db:
      image: "postgres:13.2-alpine"
      restart: always
      volumes:
        - "./data:/var/lib/postgresql/data"
        - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      networks:
          - "result-tier"
          - "back-tier"

    worker:
      image: "worker"
      restart: always
      container_name: "worker"
      build: "./worker"
      depends_on:
        - "db"
      networks:
        - "back-tier"
      environment:
        - TESLA:"tesla"

    redis:
      image: "redis:alpine"
      restart: always
      ports:
        - "6379:6379"
      networks:
        - "poll-tier"
        - "back-tier"

networks:
    poll-tier:
    result-tier:
    back-tier:

volumes:
    database-data:
